spring.application.name=bus-sig
server.port=${PORT:8081}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bus_sig}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jackson.serialization.indent-output=true

google.maps.api-key=${GOOGLE_MAPS_API_KEY:}
